const STORAGE_KEY="kintai-mobile-pro-ui-v1";
let deferredPrompt=null;
const state=loadState();
function defaults(){return {records:[],requests:[]};}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaults();}catch{return defaults();}}
function saveState(){localStorage.setItem(STORAGE_KEY, JSON.stringify(state));}
const pad=n=>String(n).padStart(2,"0");
function dateKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
function timeText(d=new Date()){return `${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function hm(mins){return `${Math.floor(mins/60)}:${pad(mins%60)}`;}
function minDiff(a,b){if(!a||!b)return 0; const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number); return Math.max(0,bh*60+bm-(ah*60+am));}
function workMinutes(rec){if(!rec?.in||!rec?.out)return 0; return Math.max(0,minDiff(rec.in,rec.out)-(rec.breakMin||60));}
function overtimeMinutes(rec){return Math.max(0,workMinutes(rec)-8*60);}
function todayRecord(){return state.records.find(r=>r.date===dateKey());}
function toast(msg){const el=document.getElementById('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),1800);}
function statusText(rec){if(!rec?.in) return '未出勤'; if(rec.in&&!rec.out) return '勤務中'; return '退勤済み';}
function getMonthSummary(){const now=new Date(); const ym=`${now.getFullYear()}-${pad(now.getMonth()+1)}`; const monthRecords=state.records.filter(r=>r.date.startsWith(ym)&&r.in); return {days:monthRecords.length,total:monthRecords.reduce((s,r)=>s+workMinutes(r),0),ot:monthRecords.reduce((s,r)=>s+overtimeMinutes(r),0)};}
function setHeaderClock(){const d=new Date(); document.getElementById('clockText').textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`; document.getElementById('dateText').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'full'}).format(d);}
setInterval(setHeaderClock,1000);
function getPosition(){return new Promise((resolve,reject)=>{ if(!navigator.geolocation) return reject(new Error('この端末は位置情報に対応していません')); const gpsEl=document.getElementById('gpsState'); gpsEl.textContent='GPS 取得中…'; gpsEl.className='status-pill neutral'; navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:Math.round(p.coords.accuracy),at:new Date().toISOString()}),e=>reject(new Error(e.code===1?'位置情報が許可されていません':'位置情報を取得できませんでした')),{enableHighAccuracy:true,timeout:12000,maximumAge:10000}); });}
async function punch(kind){const rec=todayRecord(); if(kind==='in'&&rec?.in) return toast('すでに出勤済みです'); if(kind==='out'&&!rec?.in) return toast('先に出勤してください'); if(kind==='out'&&rec?.out) return toast('すでに退勤済みです'); try{ const pos=await getPosition(); let r=todayRecord(); if(!r){r={date:dateKey(),in:null,out:null,breakMin:60,events:[]}; state.records.push(r);} const tm=timeText(); if(kind==='in'){r.in=tm; r.inGps=pos; (r.events=r.events||[]).push({type:'出勤',time:tm,gps:pos});} else {r.out=tm; r.outGps=pos; (r.events=r.events||[]).push({type:'退勤',time:tm,gps:pos});} saveState(); renderAll(); toast(`${kind==='in'?'出勤':'退勤'}を記録しました（GPS ±${pos.accuracy}m）`);}catch(err){ const gpsEl=document.getElementById('gpsState'); gpsEl.textContent='GPS 利用不可'; gpsEl.className='status-pill neutral'; toast(err.message); }}
function renderHome(){const rec=todayRecord(); const stat=statusText(rec); document.getElementById('workState').textContent=stat; const badge=document.getElementById('todayBadge'); badge.textContent=stat; badge.className=stat==='退勤済み'?'mini-badge ok':'mini-badge'; const gpsRec=rec?.outGps||rec?.inGps; const gpsEl=document.getElementById('gpsState'); if(gpsRec){gpsEl.textContent=`GPS ±${gpsRec.accuracy}m`; gpsEl.className='status-pill ok';}else{gpsEl.textContent='GPS 未取得'; gpsEl.className='status-pill neutral';} document.getElementById('todayIn').textContent=rec?.in||'--:--'; document.getElementById('todayOut').textContent=rec?.out||'--:--'; document.getElementById('todayWork').textContent=hm(workMinutes(rec)); document.getElementById('clockInBtn').disabled=!!rec?.in; document.getElementById('clockOutBtn').disabled=!rec?.in||!!rec?.out; const summary=getMonthSummary(); document.getElementById('monthDays').textContent=`${summary.days}日`; document.getElementById('monthHours').textContent=hm(summary.total); document.getElementById('monthOt').textContent=hm(summary.ot); renderRecentLogs();}
function renderRecentLogs(){const target=document.getElementById('recentLogs'); const logs=[]; [...state.records].sort((a,b)=>b.date.localeCompare(a.date)).forEach(rec=>{ if(rec.out) logs.push({date:rec.date,time:rec.out,type:'退勤',gps:rec.outGps}); if(rec.in) logs.push({date:rec.date,time:rec.in,type:'出勤',gps:rec.inGps});}); const items=logs.slice(0,6); target.innerHTML=items.length?items.map(log=>`<div class="timeline-row ${log.type==='退勤'?'out':''}"><span class="dot"></span><time>${log.time}</time><div><strong>${log.type}</strong><small>${log.date}${log.gps?` / GPS ±${log.gps.accuracy}m`:''}</small></div></div>`).join(''):`<div class="timeline-row"><span class="dot"></span><time>--:--</time><div><strong>まだ打刻がありません</strong><small>出勤ボタンから始めてください</small></div></div>`;}
function renderHistory(){const list=document.getElementById('historyList'); const rows=[...state.records].sort((a,b)=>b.date.localeCompare(a.date)); list.innerHTML=rows.length?rows.map(rec=>{ const stat=statusText(rec); return `<article class="history-card"><div class="card-head"><strong>${rec.date}</strong><span class="${stat==='退勤済み'?'mini-badge ok':'mini-badge'}">${stat}</span></div><div class="history-metrics"><div class="metric-mini"><small>出勤</small><strong>${rec.in||'-'}</strong></div><div class="metric-mini"><small>退勤</small><strong>${rec.out||'-'}</strong></div><div class="metric-mini"><small>勤務</small><strong>${hm(workMinutes(rec))}</strong></div></div><div class="gps-caption">${rec.inGps?`出勤GPS: ${rec.inGps.lat.toFixed(5)}, ${rec.inGps.lng.toFixed(5)} / ±${rec.inGps.accuracy}m`:'出勤GPS: -'}<br>${rec.outGps?`退勤GPS: ${rec.outGps.lat.toFixed(5)}, ${rec.outGps.lng.toFixed(5)} / ±${rec.outGps.accuracy}m`:'退勤GPS: -'}</div></article>`;}).join(''):`<article class="history-card"><strong>勤務履歴はまだありません</strong><div class="gps-caption">まずはホーム画面から出勤してみてください。</div></article>`;}
function renderRequests(){const list=document.getElementById('requestList'); const rows=[...state.requests].sort((a,b)=>b.id-a.id); list.innerHTML=rows.length?rows.map(req=>`<article class="request-card"><div class="card-head"><strong>${req.type}</strong><span class="mini-badge ok">${req.status}</span></div><div>${req.date}</div><p>${req.reason||'理由なし'}</p></article>`).join(''):`<article class="request-card"><strong>申請はまだありません</strong><p>休暇申請や打刻修正申請をここで確認できます。</p></article>`;}
function renderAll(){setHeaderClock(); renderHome(); renderHistory(); renderRequests();}
function addSampleData(){const now=new Date(); for(let i=1;i<=7;i++){ const d=new Date(now); d.setDate(now.getDate()-i); if(d.getDay()===0||d.getDay()===6) continue; const date=dateKey(d); if(state.records.some(r=>r.date===date)) continue; const inMin=9*60+(i%4)*3; const outMin=18*60+5+i; const inT=`${pad(Math.floor(inMin/60))}:${pad(inMin%60)}`; const outT=`${pad(Math.floor(outMin/60))}:${pad(outMin%60)}`; state.records.push({date,in:inT,out:outT,breakMin:60,inGps:{lat:35.681236,lng:139.767125,accuracy:8+i,at:new Date().toISOString()},outGps:{lat:35.681236,lng:139.767125,accuracy:10+i,at:new Date().toISOString()}});} saveState(); renderAll(); toast('デモ勤務データを追加しました');}
function navigate(viewId){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===viewId)); document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===viewId)); window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('clockInBtn').addEventListener('click',()=>punch('in')); document.getElementById('clockOutBtn').addEventListener('click',()=>punch('out')); document.getElementById('sampleBtn').addEventListener('click',addSampleData); document.getElementById('requestDate').value=dateKey();
document.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.nav))); document.querySelectorAll('.demo-action').forEach(btn=>btn.addEventListener('click',()=>toast(`${btn.dataset.demo}はデモ表示です`)));
document.getElementById('requestForm').addEventListener('submit',e=>{e.preventDefault(); const date=document.getElementById('requestDate').value; if(!date) return; state.requests.push({id:Date.now(),type:document.getElementById('requestType').value,date,reason:document.getElementById('requestReason').value.trim(),status:'申請済'}); saveState(); e.target.reset(); document.getElementById('requestDate').value=dateKey(); renderRequests(); toast('申請を保存しました');});
document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('この端末のデモデータを初期化しますか？')){state.records=[]; state.requests=[]; saveState(); renderAll(); toast('初期化しました');}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferredPrompt=e; document.getElementById('installBtn').hidden=false;});
document.getElementById('installBtn').addEventListener('click',async()=>{if(!deferredPrompt) return; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null; document.getElementById('installBtn').hidden=true;});
window.addEventListener('online',()=>document.getElementById('offlineState').textContent='オンライン'); window.addEventListener('offline',()=>document.getElementById('offlineState').textContent='オフライン');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
renderAll();
